### ISSUE TITLE
Non funziona con Kodi 18 beta

### ISSUE THREAD

**Issue by fabri2** [orione7/plugin.video.streamondemand-pureita#18]
Su Kodi 18 alpha funziona, sulle beta no. E' previsto qualche update?

**Comment by ctrlaltca** [comment]
```
15:17:02.873 T:3902751600   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: not implemented.
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.streamondemand-pureita-master/default.py", line 50, in <module>
                                                window = navigation.get_window_for_item( item )
                                              File "/storage/.kodi/addons/plugin.video.streamondemand-pureita-master/navigation.py", line 294, in get_window_for_item
                                                window = window_channels.ChannelWindow("banner.xml",plugintools.get_runtime_path())
                                              File "/storage/.kodi/addons/plugin.video.streamondemand-pureita-master/window_channels.py", line 45, in __init__
                                                self.setCoordinateResolution(0)
                                            RuntimeError: not implemented.
                                            -->End of Python script error report<--
```

Risolto commentando le linee 44 e 45 di `/storage/.kodi/addons/plugin.video.streamondemand-pureita-master/window_channels.py`:

```
#        if self.getResolution()>0:
#           self.setCoordinateResolution(0)
```

**Comment by orione7** [comment]
Fixed thanks for the Info
