### ISSUE TITLE
Addon non funzionante

### ISSUE THREAD

**Issue by gudboipino** [orione7/plugin.video.streamondemand-pureita#2]
Ci tengo a ringraziarti dell'enorme lavoro che stai svolgendo, dell'ottimo servizio e del meraviglioso addon che stai mantenendo in vita chiamato SOD-PureIta.
Purtroppo con l'ultimo update non é piu funzionante, continua ad andare nel Log di kodi o se per caso si apre tutte le voci sono vuote con messaggio "Riavviare".
Spero che la mia segnalazione ti possa aiutare a correggere i bug che si sono presentati!
Ti auguro un buon lavoro e ti ringrazio ancora per tutto quello che fai per la comunity di SOD-PureIta!!

**Comment by hitokiri8x** [comment]
```
12:20:48.792 T:1561326336   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'downloadpage'
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.streamondemand-pureita-master/default.py", line 43, in <module>
                                                updater.checkforupdates(plugin_mode=False)
                                              File "/home/pi/.kodi/addons/plugin.video.streamondemand-pureita-master/core/updater.py", line 92, in checkforupdates
                                                data = scrapertools.cache_page( REMOTE_VERSION_FILE )
                                              File "/home/pi/.kodi/addons/plugin.video.streamondemand-pureita-master/core/scrapertools.py", line 37, in cache_page
                                                return cachePage(url,post,headers,modo_cache,timeout=timeout)
                                              File "/home/pi/.kodi/addons/plugin.video.streamondemand-pureita-master/core/scrapertools.py", line 41, in cachePage
                                                data = downloadpage(url,post=post,headers=headers, timeout=timeout)
                                              File "/home/pi/.kodi/addons/plugin.video.streamondemand-pureita-master/core/scrapertools.py", line 46, in downloadpage
                                                response = httptools.downloadpage(url, post=post, headers=headers, follow_redirects = follow_redirects, timeout=timeout)
                                            AttributeError: 'module' object has no attribute 'downloadpage'
                                            -->End of Python script error report<--

```

Qualcosa mi dice che non hai committato/finito la nuova libreria per gestire i download, dato che il file httptools è vuoto!
Ripristinando il file originale scrapertools, funziona tutto ;)

**Comment by tamamma** [comment]
In che senso ripristinando scrapertools originale?
Ho rinominato quello attuale come _new e togliendo _old all'altro ma ho sempre lo stesso errore.

**Comment by cici223** [comment]
confermo addon non piu funzionante su kodi (android tv box) dopo aver eseguito l ultimo aggiornamento ieri.
va in errore all avvio, restando nella schermata di selezione degli addon.

**Comment by DarkSkull91** [comment]
Confermo anch'io...

**Comment by tobispace** [comment]
Confermo, non funziona più. Qualsiasi funzione si clicchi mostra "Rimozione effettuata - riavviare". Ovviamente cliccandolo non succede nulla. Appena hai un secondo gentilmente se puoi risolvere... Grazie :)

**Comment by noccio** [comment]
Anche a me non funziona più. Questo è il log di errore:

`17:55:39.086 T:1243173792   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--

                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!

                                            Error Type: <type 'exceptions.AttributeError'>

                                            Error Contents: 'module' object has no attribute 'downloadpage'

                                            Traceback (most recent call last):

                                              File "/storage/.kodi/addons/plugin.video.streamondemand-pureita-master/default.py", line 43, in <module>

                                                updater.checkforupdates(plugin_mode=False)

                                              File "/storage/.kodi/addons/plugin.video.streamondemand-pureita-master/core/updater.py", line 92, in checkforupdates

                                                data = scrapertools.cache_page( REMOTE_VERSION_FILE )

                                              File "/storage/.kodi/addons/plugin.video.streamondemand-pureita-master/core/scrapertools.py", line 37, in cache_page

                                                return cachePage(url,post,headers,modo_cache,timeout=timeout)

                                              File "/storage/.kodi/addons/plugin.video.streamondemand-pureita-master/core/scrapertools.py", line 41, in cachePage

                                                data = downloadpage(url,post=post,headers=headers, timeout=timeout)

                                              File "/storage/.kodi/addons/plugin.video.streamondemand-pureita-master/core/scrapertools.py", line 46, in downloadpage

                                                response = httptools.downloadpage(url, post=post, headers=headers, follow_redirects = follow_redirects, timeout=timeout)

                                            AttributeError: 'module' object has no attribute 'downloadpage'

                                            -->End of Python script error report<--
`

**Comment by DarkSkull91** [comment]
Raga, sull'aba repo c'è la versione "TEST" che funziona :) Però ho paura che tutto questo un giorno finirà... Più che altro questo è l'unico add-on che funzionava (e che funziona con la versione sull'aba repo). Mi consigliereste altri add-on simili e funzionanti? Grazie

**Comment by aeusebi** [comment]
Credo che il problema sia in parte causato da un errore nei file 'core/httptools.py' e 'servers/httptools.py' che sono vuoti. In dettaglio (plugin.video.streamondemand-pureita-5.4.91.zip):

> ls -al `find . | egrep httptools.py`
-rw-r--r-- 1 osmc osmc   1 Dec 22 09:36 ./core/httptools.py
-rw-r--r-- 1 osmc osmc 171 Dec 22 09:37 ./core/httptools.pyo
-rw-r--r-- 1 osmc osmc   0 Dec 22 09:36 ./servers/httptools.py

In questo moulo dovrebbe essere definita la funzione 'downloadpage'.
Se avvio streamondemand in questa condizione streamondemand non si avvia e ritorna l'errore di cui sopra.
Se scarico il file 'httptools.py' da pelisalacarta (https://github.com/pelisalacarta-ce/pelisalacarta-ce/raw/master/python/main-classic/core/httptools.py) e copio quel file in core:

> ls -al `find . | egrep httptools.py`
-rw-r--r-- 1 osmc osmc 10731 Dec 22 09:44 ./core/httptools.py
-rw-r--r-- 1 root root     1 Dec 22 09:44 ./core/httptools.py.ORG
-rw-r--r-- 1 osmc osmc  9196 Dec 22 09:44 ./core/httptools.pyo
-rw-r--r-- 1 osmc osmc     0 Dec 22 09:36 ./servers/httptools.py

allora streamondemand si avvia regolarmente ma quando vado in 'Ricerca Globale' ho l'errore 'Rimozione effettuata riavviare'.

**Comment by noccio** [comment]
Ho provato questa soluzione e posso confermare la correttezza

**Comment by DarkLegend11** [comment]
A me l'intero add-on non funziona, come posso risolvere per favore?
