### ISSUE TITLE
after-update exception

### ISSUE THREAD

**Issue by ciropom** [orione7/plugin.video.streamondemand-pureita#29]
Hello after the last update I can't open the plugin anymore with the following exception

```
21:07:45.010 T:546459082368   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'downloadpage'
                                            Traceback (most recent call last):
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.streamondemand-pureita-master/default.py", line 43, in <module>
                                                updater.checkforupdates(plugin_mode=False)
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.streamondemand-pureita-master/core/updater.py", line 92, in checkforupdates
                                                data = scrapertools.cache_page( REMOTE_VERSION_FILE )
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.streamondemand-pureita-master/core/scrapertools.py", line 37, in cache_page
                                                return cachePage(url,post,headers,modo_cache,timeout=timeout)
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.streamondemand-pureita-master/core/scrapertools.py", line 41, in cachePage
                                                data = downloadpage(url,post=post,headers=headers, timeout=timeout)
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.streamondemand-pureita-master/core/scrapertools.py", line 46, in downloadpage
                                                response = httptools.downloadpage(url, post=post, headers=headers, follow_redirects = follow_redirects, timeout=timeout)
                                            AttributeError: 'module' object has no attribute 'downloadpage'
                                            -->End of Python script error report<--
```

[kodi@omnes .kodi]$ kodi --version
17.6 Git:20180901-nogitfound Media Center Kodi
Copyright (C) 2005-2013 Team Kodi - http://kodi.tv

**Comment by safanaj** [comment]
Hi guys, also the massive removal of code from channels, servers and the empty httptools.py looks like cannot help.
I also notice some unresolved conflicts in channelslist.xml starting from here https://raw.githubusercontent.com/orione7/plugin.video.streamondemand-pureita/master/channels/altadefinizione01.py

I guess that the last update/merge was not very good or breaking this plugin is intentional?
this looks like the last working commit 345f48553ef3a0858437173a33bc30b3a8873ca3
