### ISSUE TITLE
Provato su windows ma non va

### ISSUE THREAD

**Issue by DinoFontana** [orione7/plugin.video.streamondemand-pureita#3]
Ciao ho provato ad installare su windows 10 home ma non riesco a farlo partire, nel log genera il seguente errore:

```
17:40:39.887 T:408   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'downloadpage'
                                            Traceback (most recent call last):
                                              File "C:\Users\ut1\AppData\Roaming\Kodi\addons\plugin.video.streamondemand-pureita-master\default.py", line 43, in <module>
                                                updater.checkforupdates(plugin_mode=False)
                                              File "C:\Users\ut1\AppData\Roaming\Kodi\addons\plugin.video.streamondemand-pureita-master\core\updater.py", line 92, in checkforupdates
                                                data = scrapertools.cache_page( REMOTE_VERSION_FILE )
                                              File "C:\Users\ut1\AppData\Roaming\Kodi\addons\plugin.video.streamondemand-pureita-master\core\scrapertools.py", line 37, in cache_page
                                                return cachePage(url,post,headers,modo_cache,timeout=timeout)
                                              File "C:\Users\ut1\AppData\Roaming\Kodi\addons\plugin.video.streamondemand-pureita-master\core\scrapertools.py", line 41, in cachePage
                                                data = downloadpage(url,post=post,headers=headers, timeout=timeout)
                                              File "C:\Users\ut1\AppData\Roaming\Kodi\addons\plugin.video.streamondemand-pureita-master\core\scrapertools.py", line 46, in downloadpage
                                                response = httptools.downloadpage(url, post=post, headers=headers, follow_redirects = follow_redirects, timeout=timeout)
                                            AttributeError: 'module' object has no attribute 'downloadpage'
                                            -->End of Python script error report<--
```

**Comment by ctrlaltca** [comment]
E' lo stesso problema descritto in #2
