### ISSUE TITLE
Rileva update e va in errore.......... forse perchè non ci sono zip nelle release ?

### ISSUE THREAD

**Issue by DjDiabolik** [orione7/plugin.video.streamondemand-pureita#30]
All'avvio rileva una nuova versione 5.4.91 ma poi va subito in errore e dice di controllare il log.

Guardandoci compare questo:
`
00:04:15.559 T:1148449536   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'zipfile.BadZipfile'>
                                            Error Contents: File is not a zip file
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.streamondemand-pureita-master/default.py", line 43, in <module>
                                                updater.checkforupdates(plugin_mode=False)
                                              File "/home/osmc/.kodi/addons/plugin.video.streamondemand-pureita-master/core/updater.py", line 197, in checkforupdates
                                                update(params)
                                              File "/home/osmc/.kodi/addons/plugin.video.streamondemand-pureita-master/core/updater.py", line 229, in update
                                                unzipper.extract(localfilename,destpathname)
                                              File "/home/osmc/.kodi/addons/plugin.video.streamondemand-pureita-master/core/ziptools.py", line 20, in extract
                                                zf = zipfile.ZipFile(file)
                                              File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
                                                self._RealGetContents()
                                              File "/usr/lib/python2.7/zipfile.py", line 813, in _RealGetContents
                                                raise BadZipfile, "File is not a zip file"
                                            BadZipfile: File is not a zip file
                                            -->End of Python script error report<--
`

Forse semplicemente perchè non esiste lo zip ?

**Comment by DjDiabolik** [comment]
Rettifico...... ho appena rifatto un'installazione pulita e riavviato il mio kodi.
Ora l'addons non parte + per niente.............
Nel log compaiono diversi errori:
00:19:00.616 T:1399837440   ERROR: Exception in thread Thread-1:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                                self.run()
                                              File "/usr/lib/python2.7/threading.py", line 754, in run
                                                self.__target(*self.__args, **self.__kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.streamondemand-pureita-master/core/update_channels.py", line 28, in update_channels
                                                xml = scrapertools.cache_page(remote_url + "channelslist.xml")
                                              File "/home/osmc/.kodi/addons/plugin.video.streamondemand-pureita-master/core/scrapertools.py", line 37, in cache_page
                                                return cachePage(url,post,headers,modo_cache,timeout=timeout)
                                              File "/home/osmc/.kodi/addons/plugin.video.streamondemand-pureita-master/core/scrapertools.py", line 41, in cachePage
                                                data = downloadpage(url,post=post,headers=headers, timeout=timeout)
                                              File "/home/osmc/.kodi/addons/plugin.video.streamondemand-pureita-master/core/scrapertools.py", line 46, in downloadpage
                                                response = httptools.downloadpage(url, post=post, headers=headers, follow_redirects = follow_redirects, timeout=timeout)
                                            AttributeError: 'module' object has no attribute 'downloadpage'
00:19:07.627 T:1679557376  NOTICE: Skin Helper Service --> Skin Helper Service version 1.1.24 started
00:19:07.630 T:1408226048  NOTICE: Skin Helper Service --> Starting WebService on port 52307
00:19:11.931 T:1433391872   ERROR: Exception in thread Thread-2:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                                self.run()
                                              File "/usr/lib/python2.7/threading.py", line 754, in run
                                                self.__target(*self.__args, **self.__kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.streamondemand-pureita-master/core/update_servers.py", line 25, in update_servers
                                                xml = scrapertools.cache_page(remote_url + "serverlist.xml")
                                              File "/home/osmc/.kodi/addons/plugin.video.streamondemand-pureita-master/core/scrapertools.py", line 37, in cache_page
                                                return cachePage(url,post,headers,modo_cache,timeout=timeout)
                                              File "/home/osmc/.kodi/addons/plugin.video.streamondemand-pureita-master/core/scrapertools.py", line 41, in cachePage
                                                data = downloadpage(url,post=post,headers=headers, timeout=timeout)
                                              File "/home/osmc/.kodi/addons/plugin.video.streamondemand-pureita-master/core/scrapertools.py", line 46, in downloadpage
                                                response = httptools.downloadpage(url, post=post, headers=headers, follow_redirects = follow_redirects, timeout=timeout)
                                            AttributeError: 'module' object has no attribute 'downloadpage'
00:19:15.715 T:1646002944 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |TBD|
00:19:18.178 T:1646002944  NOTICE: Twitch: Service: Start (ENCODED)
00:19:19.521 T:1594098432  NOTICE: Universal - An Addons Toolkit: -watchhistory- -Loading sqlite3 as DB engine version: 3.21.0
00:19:20.148 T:1594098432  NOTICE: Universal - An Addons Toolkit: -watchhistory- -
00:19:21.915 T:1662780160 WARNING: CSkinInfo: failed to load skin settings
00:19:44.615 T:1325658880   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'downloadpage'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.streamondemand-pureita-master/default.py", line 43, in <module>
                                                updater.checkforupdates(plugin_mode=False)
                                              File "/home/osmc/.kodi/addons/plugin.video.streamondemand-pureita-master/core/updater.py", line 92, in checkforupdates
                                                data = scrapertools.cache_page( REMOTE_VERSION_FILE )
                                              File "/home/osmc/.kodi/addons/plugin.video.streamondemand-pureita-master/core/scrapertools.py", line 37, in cache_page
                                                return cachePage(url,post,headers,modo_cache,timeout=timeout)
                                              File "/home/osmc/.kodi/addons/plugin.video.streamondemand-pureita-master/core/scrapertools.py", line 41, in cachePage
                                                data = downloadpage(url,post=post,headers=headers, timeout=timeout)
                                              File "/home/osmc/.kodi/addons/plugin.video.streamondemand-pureita-master/core/scrapertools.py", line 46, in downloadpage
                                                response = httptools.downloadpage(url, post=post, headers=headers, follow_redirects = follow_redirects, timeout=timeout)
                                            AttributeError: 'module' object has no attribute 'downloadpage'
                                            -->End of Python script error report<--
00:20:20.843 T:1925458432  NOTICE: Samba is idle. Closing the remaining connections

**Comment by DjDiabolik** [comment]
Forse qua il paste del log è + interpretabile:
https://paste.ubuntu.com/p/kJmv4HDNfr/

Questo dopo la sua installazione pulita e al successivo riavvio di kodi......... va in errore addirittura, se c'ho capito qualcosa, il check iniziale degli canali e server e se lo si prova ad avviare dice subito di fare riferimento al log.
